[build-system]
requires = [
    "setuptools>=42",
    ]
requires = ["setuptools", "wheel", "cython"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80
target-version = ["py310", "py311"]
